#!/usr/bin/env bash

$(git add $1)

echo "Enter commit message with ("") around it"
read message

if [ !"$message" ]
then
        echo "Please enter commit message"
fi

while [ "$message" ]
do
	if [ "$message" -eq "cancel" ]
	then
		break;
	fi

	if [ "$message" -eq "Cancel" ]
	then
                break;
        fi

	echo $(git commit -m message)
	$(git push)
done
