#!/usr/bin/env bash

$(git add $1)

echo "Enter commit message with ("") around it"
read message

for ((;;));
do
	if [ "$message" == "cancel" ]
	then
		break;
	fi

	if [ "$message" ==  "Cancel" ]
	then
		break;
        fi
	
	if [ "$message" ]
	then
		echo $(git commit -m $message)
		$(git push)
		break;
	fi
	if [ -n "$message" ]
        then
                echo "Please enter commit message"
		continue;
        fi
	echo "Do something; hit [CTRL+C] to stop!"
	sleep 10
done
