#!/usr/bin/env bash

echo "Enter file name or '.' for all (press stop to cancel)"


for ((;;));
do
	read file
	if [ "$file" == "stop" ]
        then
		kill $$
        fi

        if [ "$file" ==  "Stop" ]
        then
                kill $$
	fi
	if [[ -f $file ]]
	then 
		echo $(git add $file)
		break;
	elif [ "$file" == "." ]
	then
		echo $(git add $file)
		break;
	else
		echo "Enter file name"
		continue;
	fi
	
	sleep 15
done

echo "Enter commit message"

for ((;;));
do
	read message
	if [ "$message" == "stop" ]
	then
		break;
	fi

	if [ "$message" ==  "Stop" ]
	then
		break;
        fi
	
	if [ "$message" ]
	then
		echo $(git commit -m $message)
		$(git push)
		break;
	fi
	if [ "$message" == "" ]
        then
                echo "Please enter commit message"
		continue;
        fi
	sleep 15
done
